lang: en
project:
  type: book
  output-dir: docs
  resources: resources
execute:
  freeze: auto
lightbox: true
anchor-sections: true
book:
  title: Installing R/RStudio Guide
  subtitle: ''
  author:
  - orcid: 0000-0002-4191-5245
    name:
      family: Bartlett
      given: James
  doi: ''
  license: CC-BY
  description: This guide provides instructions for installing R/RStudio for students at the University of Glasgow.
  cover-image: images/logos/logo.png
  image: images/logos/logo.png
  favicon: images/logos/logo.png
  cookie-consent: false
  google-analytics: ''
  page-navigation: true
  search: true
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer: CC-BY (2024) James Bartlett
  chapters:
  - index.qmd
  - installing-r-windows.qmd
  - installing-r-mac.qmd
  - installing-r-library.qmd
  - updating-r.qmd
  - install-tidytex.qmd
bibliography: include/references.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
